spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_db
    username: postgres
    password: p.postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
    open-in-view: false
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 10


logging:
  level:
    ROOT: INFO




